<?php

/*********************************************************************
* Extension configuration file for ext "lp_fussballde".
*
* Generated by ext 20-06-2014 08:52 UTC
*
* https://github.com/t3elmar/Ext
*********************************************************************/

$EM_CONF[$_EXTKEY] = array (
  'title' => 'Fussball.de',
  'description' => 'Bindet Begegnungen und Spielplaene von Fussball.de ueber JavaScript ein. Anmeldung auf Fussball.de ist noetig!',
  'category' => 'plugin',
  'author' => 'Lars Malach',
  'author_email' => 'Lars@Malach.de',
  'author_company' => '',
  'dependencies' => '',
  'shy' => '',
  'priority' => '',
  'module' => '',
  'state' => 'stable',
  'internal' => '',
  'uploadfolder' => 0,
  'createDirs' => '',
  'modify_tables' => '',
  'clearCacheOnLoad' => 0,
  'lockType' => '',
  'version' => '3.0.8',
  'constraints' => 
  array (
    'depends' => 
    array (
      'typo3' => '6.0.0-6.2.99',
    ),
    'conflicts' => 
    array (
    ),
    'suggests' => 
    array (
    ),
  ),
  'user' => 'lars85',
  'comment' => 'Enables TYPO3 Version 6.2 Support',
);

?>