<?php

/*********************************************************************
* Extension configuration file for ext "lp_fussballde".
*
* Generated by ext 04-08-2013 20:35 UTC
*
* https://github.com/t3elmar/Ext
*********************************************************************/

$EM_CONF[$_EXTKEY] = array (
  'title' => 'Fussball.de',
  'description' => 'Bindet Begegnungen und Spielplaene von Fussball.de über JavaScript ein. Anmeldung auf Fussball.de ist noetig!',
  'category' => 'plugin',
  'author' => 'Lars Peipmann',
  'author_email' => 'Lars@Peipmann.de',
  'author_company' => '',
  'dependencies' => '',
  'shy' => '',
  'priority' => '',
  'module' => '',
  'state' => 'stable',
  'internal' => '',
  'uploadfolder' => 0,
  'createDirs' => '',
  'modify_tables' => '',
  'clearCacheOnLoad' => 0,
  'lockType' => '',
  'version' => '3.0.6',
  'constraints' => 
  array (
    'depends' => 
    array (
      'typo3' => '6.0.0-6.1.99',
    ),
    'conflicts' => 
    array (
    ),
    'suggests' => 
    array (
    ),
  ),
  'user' => 'lars85',
  'comment' => 'Kleine Code Cleanups',
);

?>
