# This is the project specific Settings.yml file.
# Place Sphinx specific build information here.
# Settings given here will replace the settings of 'conf.py'.

---
conf.py:
  copyright: 1992-2013
  project: TYPO3 Extension "lp_fussballde_f4x"
  version: 3.0.3
  release: 3.0.3
...
